full_stack/config/routes.rb
Rails.application.routes.draw do
  get 'herbs' => 'herb#index', as: 'herbs'
  get 'herbs/new' => 'herb#new', as: 'new_herb'
  get 'herbs/:id' => 'herb#show', as: 'herb'
  post 'herbs' => 'herb#create'
  delete 'herbs/:id' => 'herb#destroy', as: 'delete_herb'
  get 'herbs/:id/edit' => 'herb#edit', as: 'edit_herb'
  patch 'herbs/:id' => 'herb#update'
end

full_stack/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

full_stack/app/models/herb.rb
class Herb < ApplicationRecord
end

full_stack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

full_stack/app/controllers/herb_controller.rb
class HerbController < ApplicationController
  def index
    @herbs = Herb.all
  end

  def show
    @herb = Herb.find(params[:id])
  end

  def new
    @herb = Herb.new
  end

  def create
    @herb = Herb.create(herb_params)
    if @herb.valid?
      redirect_to herbs_path
    else
      redirect_to new_herb_path
    end
  end

  def destroy
    @herb = Herb.find(params[:id])
    if @herb.destroy
      redirect_to herbs_path
    else
      redirect_to herb_path(@herb)
    end
  end

  def edit
    @herb = Herb.find(params[:id])
  end

  def update
    @herb = Herb.find(params[:id])
    @herb.update(herb_params)
    if @herb.valid?
      redirect_to herb_path(@herb)
    else
      redirect_to edit_herb_path(@herb)
    end
  end

  private
  def herb_params
    params.require(:herb).permit(:name, :is_watered)
  end
end

full_stack/app/helpers/application_helper.rb
module ApplicationHelper
end

full_stack/app/views/herb/edit.html.erb
<h3>Edit an Herb</h3>

<%= form_with model: @herb, method: :patch, local: true do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name%>
  <br />
  <%= form.radio_button :is_watered, "yes"%>
  <%= form.label :is_watered, "Herb is watered"%>
  <br />
  <%= form.radio_button :is_watered, "no"%>
  <%= form.label :is_watered, "Herb is not watered"%>
  <br />
  <%= form.submit 'Edit Herb'%>
  <%= form.submit 'Clear', :type => 'reset' %>
<% end %>

<br />
<p>Back to <%= link_to 'All the Herbs', herbs_path %></p>

full_stack/app/views/herb/index.html.erb
<h1>Herb Garden App</h1>

<ul>
  <% @herbs.each do |herb| %>
    <li>
      <%= link_to herb.name, herb_path(herb) %>
    </li>
  <% end %>
</ul>

<br />
<%= link_to 'Add new herb', new_herb_path %>

full_stack/app/views/herb/new.html.erb
<h3>Create a New Herb</h3>

<%= form_with model: @herb, local: true do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name%>
  <br />
  <%= form.radio_button :is_watered, "yes"%>
  <%= form.label :is_watered, "Herb is watered"%>
  <br />
  <%= form.radio_button :is_watered, "no"%>
  <%= form.label :is_watered, "Herb is not watered"%>
  <br />
  <%= form.submit 'Add Herb'%>
  <%= form.submit 'Clear', :type => 'reset' %>
<% end %>

<br />
<p>Back to <%= link_to 'All the Herbs', herbs_path %></p>

full_stack/app/views/herb/show.html.erb
<h3><%= @herb.name %></h3>
<p>Is watered: <%= @herb.is_watered %></p>

<p>Back to <%= link_to 'All the Herbs', herbs_path %></p>
<br />
<%= link_to 'Delete Herb', delete_herb_path(@herb), method: :delete, data: { confirm: 'Are you sure?' } %>
<br />
<%= link_to 'Edit Herb', edit_herb_path %>

full_stack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>